const actions = {
    SET_USERS_DATA: 'SET_USERS_DATA',
    DELETE_USERS_DATA: 'DELETE_USERS_DATA',
    SET_COLUMNS_NAME: 'SET_COLUMNS_NAME',
    CHANGE_AUTH_STATUS: 'CHANGE_AUTH_STATUS',
    CHANGE_MODAL_STATE: 'CHANGE_MODAL_STATE',
    CHANGE_USER_SHOW_MODAL: 'CHANGE_USER_SHOW_MODAL',
    CHANGE_DELETE_MODAL_STATE: 'CHANGE_DELETE_MODAL_STATE',
    ERROR_REGISTER: 'ERROR_REGISTER',
    CLEAR_ERRORS: 'CLEAR_ERRORS',
    ERROR_LOGIN: 'ERROR_LOGIN',
    ERROR_DELETE: 'ERROR_DELETE'
};

export default actions;